// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChangeColor: typeof import('./src/components/ChangeColor.vue')['default']
    DebouncingExample: typeof import('./src/components/DebouncingExample.vue')['default']
    DynamicProp: typeof import('./src/components/DynamicProp.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QrLoginExample: typeof import('./src/components/QrLoginExample.vue')['default']
    TemplateSyntax: typeof import('./src/components/TemplateSyntax.vue')['default']
  }
}

export { }
