// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    ChangeColor: typeof import('./src/components/ChangeColor.vue')['default']
    ComponentBasis: typeof import('./src/components/ComponentBasis.vue')['default']
    ComputedProperties: typeof import('./src/components/ComputedProperties.vue')['default']
    DebouncingExample: typeof import('./src/components/DebouncingExample.vue')['default']
    DynamicProp: typeof import('./src/components/DynamicProp.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    QrLoginExample: typeof import('./src/components/QrLoginExample.vue')['default']
    ReactiveRef: typeof import('./src/components/ReactiveRef.vue')['default']
    Slot: typeof import('./src/components/Slot.vue')['default']
    SlotExample: typeof import('./src/components/SlotExample.vue')['default']
    TemplateSyntax: typeof import('./src/components/TemplateSyntax.vue')['default']
    Watcher: typeof import('./src/components/Watcher.vue')['default']
  }
}

export { }
